name: Release to Clojars

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@12
        with:
          cli: latest

      - name: Build jar
        run: clojure -T:build jar

      - name: Deploy to Clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -M:deploy deploy com.github.clojure-finance/edgarjure target/edgarjure-0.1.0.jar target/classes/META-INF/maven/com.github.clojure-finance/edgarjure/pom.xml
